- name: Install Docker
  hosts: all
  become: true
    
  tasks:   
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python3
        - python3-pip
        
    - name: Install Python dependencies
      pip:
        name: requests
        state: present
        
    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        description: Docker CE repository
        baseurl: https://download.docker.com/linux/rhel/9/x86_64/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/rhel/gpg
        
    - name: Install Docker
      yum:
        name: docker-ce
        state: latest
        
    - name: Install Java
      yum:
        name: java
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Crea un Docker network 
      docker_network:
        name: primo_net
        ipam_config:
          - subnet: 192.168.2.0/24
            gateway: 192.168.2.1
            iprange: 192.168.2.0/24
            
    - name: Pull JenkinsM
      community.docker.docker_image:
        name: jenkins/jenkins:lts
        source: pull
        
    - name: Pull JenkinsS
      community.docker.docker_image:
        name: jenkins/inbound-agent
        source: pull
        
    - name: Crea ContainerMaster
      docker_container:
        name: ContainerM
        image: jenkins/jenkins:lts
        state: started
        networks:
          - name: primo_net
            ipv4_address: "192.168.2.2"
        ports:
          - "8080:8080"  # Porta per l'interfaccia web di Jenkins
          - "50000:50000"  # Porta per la comunicazione con lo slave
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
     
    - name: Create Jenkins Slave Container (ContainerS)
      docker_container:
        name: ContainerS
        image: jenkins/inbound-agent
        networks:
          - name: primo_net
            ipv4_address: "192.168.2.3"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          JENKINS_URL: "http://192.168.2.2:8080/"
          JENKINS_AGENT_NAME: "ContainerS"
          JENKINS_AGENT_WORKDIR: "/home/jenkins"
          JENKINS_SECRET: "jenkins_secret"     #da inserire password
        state: started
        
          #- name: Step 4 
          # hosts: ContainerS
          #  tasks: 
    - name: Download Helm installation script
      get_url:
         url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
         dest: /tmp/get_helm.sh
         mode: '0755'

    - name: Run Helm installation script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
      register: helm_install_result
      changed_when: false

    - name: Add /usr/local/bin to PATH
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:/usr/local/bin'
      when: helm_install_result.rc == 0

    - name: Add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
        state: present
        update_cache: yes

    - name: Install Kubelet
      apt:
        name: kubelet=1.29.*
        state: present
        update_cache: true

    - name: Install Kubeadm
      apt:
        name: kubeadm=1.29.*
        state: present

    - name: Enable the Kubelet service
      service:
        name: kubelet
        enabled: yes

    - name: Install Kubectl
      apt:
        name: kubectl=1.29.*
        state: present
        force: yes


        #    - name: Creazione namespace formazione_sou
        #      kubernetes.core.k8s:
        #        name: formazione_sou
        #        api_version: v1
        #        kind: Namespace
        #        state: present

