apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom.fullname" . }}
  labels:
    {{- include "custom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80 
      targetPort: 8000
      nodePort: 31000
      protocol: TCP
  selector:
    {{- include "custom.selectorLabels" . | nindent 4 }}
#    app: app.py